name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - run: echo "${{github.event.pull_request.head.repo.full_name}}"
      - run: echo "${{github.event.pull_request.base.repo.full_name}}"
      - uses: Automattic/action-required-review@v2.2.2
        with:
          requirements: |
            - paths: unmatched
              teams:
                - "leads"
          status: Required Review
          fail: true
          token: ${{ github.token }}
