name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]
    

jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - name: auto action
        uses: Automattic/action-required-review@v3
        with:
          token: ${{github.token}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - "@yash-sharma-robomq"
          status: Required Review
          fail: true
          
      - name: fetch api second
        run: |
          response = "$( gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name) {
                issues(states:OPEN){
                  totalCount
                }
              }
            }
          ' --jq '.data.repository.issues.totalCount')"
          
          echo 'hii...'$response
          
      
      - name: Fetch API Data
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
          --url "https://api.github.com/orgs/yash95751/teams" \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: Bearer $GH_TOKEN"
          
          
          
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: http://api.github.com
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"} }'
              
