name: Pull request review is requested
on:
  pull_request_review:
 # pull_request:
  #  types: [ opened, reopened, synchronize ]
    
permissions: write-all
jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - name: auto action
        uses: Automattic/action-required-review@v3
        with:
          token: ${{github.token}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - "@yash-sharma-robomq"
          status: Atleast a review required from team leads
          fail: true
      
      - name: Fetch API Data
        run: |
            curl --request GET 'https://api.github.com/orgs/yash95751/teams/leads/members' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{github.token}}' \
            --header 'Cookie: _octo=GH1.1.856630408.1662440634; logged_in=no'
