name: Pull request review is requested
on:
  pull_request_review:
 # pull_request:
  #  types: [ opened, reopened, synchronize ]
    

jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - name: auto action
      - uses: Automattic/action-required-review@v3
        with:
          token: ${{github.token}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - "@yash-sharma-robomq"
          status: Atleast a review required from team leads
          fail: true
          
   #   - name: fetch api second
    #    run: |
     #     curl -H "Authorization: ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.v4.idl" \
      #    https://api.github.com/graphql
          
       #   echo 'hii...'$response
          
      
      - name: Fetch API Data
        run: |
            curl -k --location --request GET 'https://api.github.com/orgs/yash95751/teams/leads/members' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer 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' \
            --header 'Cookie: _octo=GH1.1.856630408.1662440634; logged_in=no'
          
          
          
  #    - name: Fetch API Data 📦
  #      uses: JamesIves/fetch-api-data-action@v2
  #      with:
  #        endpoint: http://api.github.com
  #        configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"} }'
              
