name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]
    

jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - run: echo "${{github.event.pull_request.head.repo.full_name}}"
      - run: echo "${{github.event.pull_request.base.repo.full_name}}"
      - name: auto action
        uses: Automattic/action-required-review@v3
        with:
          token: ${{secrets.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}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - checks
              - leads
          status: Required Review
          fail: true
          
          
          
          
          
          
          
          
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: http://api.github.com
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"} }'
    
          
          
          
          
          
          
          
          
      #- name: Fetch API Data
        #env:
         # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: |
          #curl --request GET \
          #--url "https://api.github.com/orgs/yash95751/teams" \
          #--header "Accept: application/vnd.github.v3+json" \
          #--header "Authorization: Bearer $GH_TOKEN"
