name: Pull request review is requested
on:
  pull_request_review:
 # pull_request:
  #  types: [ opened, reopened, synchronize ]
    

permissions: write-all


jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - name: auto action
        uses: Automattic/action-required-review@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - "@yash-sharma-robomq"
          status: Atleast a review required from team leads
          fail: true
      
      - name: Fetch API Data
        run: |
              curl https://jsonplaceholder.typicode.com/posts?userId=1