name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - run: echo "${{github.event.pull_request.head.repo.full_name}}"
      - run: echo "${{github.event.pull_request.base.repo.full_name}}"
      - name: auto action
        uses: Automattic/action-required-review@v2.2.2
        with:
          requirements: |
            - paths: unmatched
              teams:
                - leads
          status: Required Review
          fail: true
          token: ${{ github.token }}
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/orgs/yash95751/teams
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'
