name: Pull request review is requested
on:
  pull_request_review:
 # pull_request:
  #  types: [ opened, reopened, synchronize ]
    

permissions: write-all


jobs:
  check:
    name: Checking required reviews
    runs-on: self-hosted  

    steps:
      - name: auto action
        uses: Automattic/action-required-review@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          requirements: |
           - name: Everything else
             paths: unmatched
             teams:
              - "@yash-sharma-robomq"
          status: Atleast a review required from team leads
          fail: true
      
      - name: Fetch API Data
        run: |
            curl --location --request GET 'https://alpha.robomq.io/hire2retire/adp_mock_server/api/v2/workers' \
              --header 'Content-Type: application/x-www-form-urlencoded' \
              --header 'Authorization: Bearer 327c6639-453b-4821-a8c4-97df4eccb15f'